path:
  prj_ref: null
  res_ref: /img/files
  upload_ref: /upload
  backup_ref: /app/backup
  cache_ref: /app/cache/
  cache_ttl: 86400;
  theme_ref: /bundles/admin

database:
  dbname:   database  
  user:     username
  password: password
  host:     localhost
  driver:   pdo_mysql
  
captcha:  
  hash: secretkey

developer:
  username: dev
  password: password  